# Generated by Django 5.2.4 on 2025-09-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sentMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderName', models.CharField(blank=True, max_length=40, null=True)),
                ('senderEmail', models.CharField(blank=True, max_length=40, null=True)),
                ('senderPhone', models.CharField(blank=True, max_length=40, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['senderEmail'], name='subscriptio_senderE_498edf_idx'), models.Index(fields=['senderPhone'], name='subscriptio_senderP_4a1420_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='subscriptio_type_728074_idx')],
            },
        ),
    ]
